server.port=8090
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform = org.hibernate.dialect.MySQL8Dialect
spring.datasource.url=jdbc:mysql://localhost:3306/mysql
spring.datasource.username=root
spring.datasource.password=Prepare@123$
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update
spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.mustache
# keys for JPA
javax.persistence.jdbc.driver = org.h2.Driver
javax.persistence.jdbc.url = jdbc:h2:mem:mysql
javax.persistence.jdbc.user = root
javax.persistence.jdbc.password = Prepare@123$